"""MARG architecture dimensions (match Risky_gym / paper)."""

MARG_PROPRIO_DIM = 43
MARG_HISTORY_LEN = 6
MARG_HISTORY_DIM = MARG_PROPRIO_DIM * MARG_HISTORY_LEN  # 258
MARG_HEIGHT_MAP_DIM = 187
MARG_ELEVATION_OUT_DIM = 16
MARG_ESTIMATOR_OUT_DIM = 7
MARG_ESTIMATOR_VEL_DIM = 3
MARG_ESTIMATOR_CONTACT_DIM = 4
MARG_CRITIC_PRIV_DIM = 42
